### ISSUE TITLE
isLessVariable in stylelint v15

### ISSUE THREAD

**Issue by DevYimo** [ssivanatarajan/stylelint-less#11]
Hi, 
I just updated package in my project to 1.0.7 and found out, that stylelint v15 removed file "utils/isLessVariable.js" which is used here (color-hex-case).
Can we please fix it here? :)

Thank you!

**Comment by ThornWu** [comment]
Related Stylelint PR: https://github.com/stylelint/stylelint/pull/6995

**Comment by timi137137** [comment]
Need a quick fix pls

**Comment by Ghost-J** [comment]
Is there an ETA on when @foosbar's PR will be merged?
