### ISSUE TITLE
Migrating to a monorepo

### ISSUE THREAD

**Issue by ubermanu** [ssivanatarajan/stylelint-less#15]
Hey Sivanatarajan,

I sent you an email earlier about my project of migrating all the `stylelint-less` repositories into a single organisation

This is what I have actually: https://github.com/stylelint-less/stylelint-less (the PR #14 is included)

Hit me up if you are interested!

**Comment by SevenOutman** [comment]
May we just publish the updated package as something like `@stylelint-less/stylelint-plugin` and `@stylelint-less/config-recommended`?

**Comment by ubermanu** [comment]
can do that around the 16th of August once I come back

**Comment by ssivanatarajan** [comment]
I am fine with moving packages to stylint-less org. We can proceed.  Thank you @ubermanu @SevenOutman  for this initiative.

**Comment by ubermanu** [comment]
Nice, i sent you an inivite to the org 😄

**Comment by ubermanu** [comment]
Hey @ssivanatarajan! I need publish access on NPM to both of these packages:

- stylelint-less
- stylelint-config-recommended-less

(See https://github.com/stylelint-less/stylelint-less/issues/10)

Thank you!
