### ISSUE TITLE
says SCSS in README

### ISSUE THREAD

**Issue by snebjorn** [ssivanatarajan/stylelint-less#2]
https://github.com/ssivanatarajan/stylelint-less/blob/5119239ba206a4caeb23e63a127d810bc211193d/README.md?plain=1#L14

> All rules from **stylelint-scss** need to be namespaced with `less`.

I believe it should say "stylelint-less"

as it'll error on on https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-each-key-value-single-line

`✖  Unknown rule less/at-each-key-value-single-line`

**Comment by ssivanatarajan** [comment]
Thanks for reporting, changed it to "stylelint-less"
