### ISSUE TITLE
Stylelint v15

### ISSUE THREAD

**Issue by DevYimo** [ssivanatarajan/stylelint-less#9]
Hello,
Would be possible to add suppport for stylelint v15

Thank you :-)

**Comment by Djspaceg** [comment]
It looks like the origin of this issue was when adding `stylelint` v14. It should be as easy as bumping it up to 15 from 14.

**Comment by admin8756** [comment]
WARN  Issues with peer dependencies found
.
└─┬ stylelint-less 1.0.6
  └── ✕ unmet peer stylelint@^14.9.1: found 15.6.2

**Comment by ssivanatarajan** [comment]
Added support for v15
